apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: superset
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/saivamshi465/superset.git
  ref:
    branch: master
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: superset
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/superset/
      version: "0.6.3"
      sourceRef:
        kind: GitRepository
        name: superset
        namespace: flux-system
     
